# Config file for automatic testing at travis-ci.org

sudo: false
language: python

matrix:
  include:
    - python: 3.6
      env: TOX_ENV=py36
    - python: 3.7
      dist: xenial
      sudo: required
      env: TOX_ENV=py37
    - python: 3.7
      dist: xenial
      sudo: required
      env: TOX_ENV=flake8
    - python: 3.8
      dist: xenial
      sudo: required
      env: TOX_ENV=py38

install:
  - pip install tox

script:
  - tox -e $TOX_ENV

before_cache:
  - rm -rf $HOME/.cache/pip/log

cache:
  directories:
    - $HOME/.cache/pip
